packages:
  - 'apps/*'

autoInstallPeers: false
minimumReleaseAge: 720
allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': true
  cloudflared: true
  cpu-features: true
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: true

patchedDependencies:
  '@deepseek-ai/dsh-subprocess-local@0.1.1-rc.2': patches/@deepseek-ai__dsh-subprocess-local@0.1.1-rc.2.patch
  '@deepseek-ai/dsh-web-app@0.1.1-rc.2': patches/@deepseek-ai__dsh-web-app@0.1.1-rc.2.patch
  '@deepseek-ai/dsh@0.1.1-rc.2': patches/@deepseek-ai__dsh@0.1.1-rc.2.patch
