packages:
  - 'apps/dsh-desktop'

autoInstallPeers: false
minimumReleaseAge: 720
supportedArchitectures:
  os:
    - current
    - darwin
  cpu:
    - current
    - x64
    - arm64
overrides:
  ws: 8.21.3
allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': true
  cloudflared: true
  cpu-features: true
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: true

patchedDependencies:
  '@deepseek-ai/dsh-web-app@0.1.5-rc.2': patches/@deepseek-ai__dsh-web-app@0.1.5-rc.2.patch
  '@deepseek-ai/dsh@0.1.5-rc.1': patches/@deepseek-ai__dsh@0.1.5-rc.1.patch
  '@electron/universal@2.0.3': patches/@electron__universal@2.0.3.patch
