export const COMMUNITY_QQ_URL = 'https://qm.qq.com/q/vehlNjaeye'
export const GITHUB_DOWNLOADS_URL = 'https://github.com/gxygxy1025-lab/-deepseek-harness-desktop/releases/latest'
export const GITHUB_FEEDBACK_URL = 'https://github.com/gxygxy1025-lab/-deepseek-harness-desktop/issues/new/choose'
export const GITHUB_PROJECT_URL = 'https://github.com/gxygxy1025-lab/-deepseek-harness-desktop'
export const PRIVACY_POLICY_URL = 'https://github.com/gxygxy1025-lab/-deepseek-harness-desktop/blob/release/core-1.0.0/PRIVACY.md'
